---
title: "data"
author: "Yooby"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
source(here::here("script/setup.R"))
```

## Data

```{r}
# Upload the data
setwd(here::here("data/"))
GermanCreditRaw <- read_csv2("GermanCredit.csv")
```

<div>

The initial dataset about German credit data contains `r ncol(GermanCreditRaw)` variables and `r nrow(GermanCreditRaw)` observations.

</div>

```{r}
# Removing the first column, aka "OBS#, not useful.

GermanCredit <- GermanCreditRaw %>% 
  select(-c("OBS#"))

# Coding as factors the following variables: CHK_ACCT, HISTORY, NEW_CAR, USED_CAR, FURNITURE, RADIO/TV, EDUCATION, RETRAINING, SAV_ACCT, EMPLOYMENT, MALE_DIV, MAL_SINGLE, MALE_MAR_WID, CO-APPLICANT, GUARANTOR, PRESENT_RESIDENT, REAL_ESTATE, PROP_UNKN_NONE, OTHER_INSTALL, RENT, OWN_RES, JOB, TELEPHONE, FOREIGN and RESPONSE.

factor_column <- c("CHK_ACCT", "HISTORY", "NEW_CAR", "USED_CAR", "FURNITURE", "RADIO/TV", "EDUCATION", "RETRAINING", "SAV_ACCT", "EMPLOYMENT", "MALE_DIV", "MALE_SINGLE", "MALE_MAR_or_WID", "CO-APPLICANT", "GUARANTOR", "PRESENT_RESIDENT", "REAL_ESTATE", "PROP_UNKN_NONE", "OTHER_INSTALL", "RENT", "OWN_RES", "JOB", "TELEPHONE", "FOREIGN", "RESPONSE")

GermanCredit[,factor_column] <- lapply(GermanCredit[,factor_column], factor)
```

```{r}
# Write csv file
setwd(here::here("data/"))
write_csv(GermanCredit, "GermanCreditClean.csv")
```

