
```{r setup, include=FALSE}
source(here::here("script/setup.R"))
```

```{r}
setwd(here::here("data/"))
GermanCredit <- read_csv("GermanCreditClean.csv")
```

## Exploratory Data Analysis

```{r}
# GermanCredit accepted
YES_GC <- filter(GermanCredit,RESPONSE=="1")
```

```{r}
# GermanCredit refused
NO_GC <- filter(GermanCredit,RESPONSE=="0")
```

The dataset is related to the German Credit. Each applicant is described by 30 variables and the credit application is graded by good or bad.

Let's have a look at the distribution of the applications graded as good and bad

```{r, message=FALSE}
# Distribution of the grade per credit applications
GermanCredit %>% 
  ggplot(aes(x = as.factor(RESPONSE), fill=as.factor(RESPONSE))) +
  geom_bar() +
  labs(title = "Number of credit applications per grade",
       y = "Number",
       x = "Grade") +
  theme(legend.position="none") +
  scale_x_discrete(label=c("0"="bad", "1"="good")) +
  scale_fill_manual(values = alpha(c("red3", "springgreen4"), .5))
```

```{r}
# Distribution of the continuous variables, i.e. duration, amount, age
# Here duration

p.duration <- GermanCredit %>% 
  ggplot(aes(x = DURATION, y = as.factor(RESPONSE), fill = as.factor(RESPONSE))) +
  geom_boxplot() +
  labs(title = "Duration of the credit applications per grade",
       x = "Months",
       y = "Grade") +
  scale_y_discrete(label=c("0"="bad", "1"="good")) +
  theme(legend.position="none") +
  scale_fill_manual(values = alpha(c("red3", "springgreen4"), .5))

p.duration

# Nothing to note
```


```{r}
# Same as above, for amount
p.amount <- GermanCredit %>% 
  ggplot(aes(x = AMOUNT, y = as.factor(RESPONSE), fill=as.factor(RESPONSE))) +
  geom_boxplot() +
  labs(title = "Amount of the credit applications per grade",
       x = "DM",
       y = "Grade") +
  scale_y_discrete(label=c("0"="bad", "1"="good")) +
  theme(legend.position="none") +
  scale_fill_manual(values = alpha(c("red3", "springgreen4"), .5))

p.amount

# A lot of outliers for the good applications
```

```{r}
# Same as above, for age

p.age <- GermanCredit %>% 
  ggplot(aes(x = AGE, y = as.factor(RESPONSE), fill=as.factor(RESPONSE))) +
  geom_boxplot() +
  labs(title = "Age of the credit applicants",
       x = "Years",
       y = "Grade") +
  scale_y_discrete(label=c("0"="bad", "1"="good")) +
  theme(legend.position="none") +
  scale_fill_manual(values = alpha(c("red3", "springgreen4"), .5))

p.age

# One outlier to recode - 75 years old instead of 125 years old
```


```{r, include=FALSE}
# let's check if old people have basically more credit than young people
mean_yes<-mean(YES_GC$AGE)
mean_yes

mean_no<-mean(NO_GC$AGE)
mean_no

# age does not seem to be a key criterion 
```


```{r}
# correlation matrix

#head(YES_GC)
#corgc <- cor(GermanCredit)
#corgc

#creation of a new dataset
cordata_fin <- GermanCredit[, c("CHK_ACCT", "HISTORY", "AMOUNT", "SAV_ACCT", "NUM_CREDITS", "RESPONSE") ] 
ggpairs(cordata_fin, title="Correlogram on financial data")

cordata_own <- GermanCredit[, c("NEW_CAR", "USED_CAR", "FURNITURE", "RADIO/TV", "RESPONSE") ]
ggpairs(cordata_own, title="Correlogram on owned products data")

cordata_pro <- GermanCredit[, c("JOB", "EDUCATION", "RETRAINING", "EMPLOYMENT", "RESPONSE") ] 
ggpairs(cordata_pro, title="Correlogram on professional data")

cordata_immo <- GermanCredit[, c("INSTALL_RATE", "REAL_ESTATE", "PRESENT_RESIDENT", "PROP_UNKN_NONE", "RENT", "OWN_RES", "RESPONSE") ]
ggpairs(cordata_immo, title="Correlogram on real estate data")

cordata_demo <- GermanCredit[, c("MALE_DIV", "MALE_SINGLE", "MALE_MAR_or_WID", "AGE", "FOREIGN", "RESPONSE") ] 
ggpairs(cordata_demo, title="Correlogram on demographic data")

#cor<-ggpairs(GermanCredit, title="correlogram with ggpairs()") 
```

```{r}
# create an average profile of yes person

# remove OBS column
Yes_profil<- YES_GC %>% 
  select("CHK_ACCT", "DURATION", "HISTORY", "NEW_CAR", "USED_CAR", "FURNITURE", "RADIO/TV", "EDUCATION", "RETRAINING", "AMOUNT", "SAV_ACCT", "EMPLOYMENT", "INSTALL_RATE", "MALE_DIV", "MALE_SINGLE", "MALE_MAR_or_WID", "CO-APPLICANT", "GUARANTOR", "PRESENT_RESIDENT", "REAL_ESTATE", "PROP_UNKN_NONE", "AGE", "OTHER_INSTALL", "RENT", "OWN_RES", "NUM_CREDITS", "JOB", "NUM_DEPENDENTS", "TELEPHONE", "FOREIGN")

# take the mean of each column
Yes_profil <- summarize_all(Yes_profil, mean)

# transform table in matrix
#Yes_profil <- data.frame(Yes_profil)
#Yes_profil <- apply(as.matrix.noquote(Yes_profil),2,as.numeric)

# show matrix through lolipop plot 
Yes_profil <- data.frame(
  x=c('CHK_ACCT', 'DURATION', 'HISTORY', 'NEW_CAR', 'USED_CAR', 'FURNITURE', 'RADIO.TV', 'EDUCATION', 'RETRAINING', 'AMOUNT', 'SAV_ACCT', 'EMPLOYMENT', 'INSTALL_RATE', 'MALE_DIV', 'MALE_SINGLE', 'MALE_MAR_or_WID', 'CO.APPLICANT', 'GUARANTOR', 'PRESENT_RESIDENT', 'REAL_ESTATE', 'PROP_UNKN_NONE', 'AGE', 'OTHER_INSTALL', 'RENT', 'OWN_RES', 'NUM_CREDITS', 'JOB', 'NUM_DEPENDENTS', 'TELEPHONE', 'FOREIGN'),
  y=abs(rnorm(30))
)
```

```{r}
graph_yes_profil <- ggplot(Yes_profil, aes(x=x, y=y)) +
  geom_segment( aes(x=x, xend=x, y=0, yend=y), color="skyblue") +
  geom_point( color="blue", size=4, alpha=0.6) +
  labs(
  title = "Mean of a YES profils",
  y = "Variables name", x = "Value"
)+
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank() 
)

graph_yes_profil

#barplot(prop.table(Yes_profil) * 100, horiz=TRUE, main = "Relative frequency (%)", col = rainbow(3))
```
```


